In [7]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [8]:
def acquire_data():
    '''
    Acquire the sales dataset from local cached file or if local file
    does not exits, then download the data from data.world.
    '''
    # set the filename
    filename = 'sales.csv'
    if os.path.exists(filename):
        # if local file exists
        # display status message
        print('Opening data from local file.')
        # open the local data
        df = pd.read_csv(filename)
    else:
        # if the local file does not exist, download the data
        # display status message
        print('Local file not found')
        print('Downloading dataset')
        # download the data from data.world
        df = pd.read_excel('https://query.data.world/s/fhfoecpnngvcahqseb5ai6daubh4gk?dws=00000')
        # create a local cache of the data
        df.to_csv(filename, index=False)
        
    # return the acquired data
    return df

In [3]:
df = acquire_data()

Opening data from local file.


In [4]:
df.head()

Date    Year     Month  Customer Age Customer Gender        Country  \
0  2016-02-19  2016.0  February          29.0               F  United States   
1  2016-02-20  2016.0  February          29.0               F  United States   
2  2016-02-27  2016.0  February          29.0               F  United States   
3  2016-03-12  2016.0     March          29.0               F  United States   
4  2016-03-12  2016.0     March          29.0               F  United States   

        State Product Category     Sub Category  Quantity  Unit Cost  \
0  Washington      Accessories  Tires and Tubes       1.0      80.00   
1  Washington         Clothing           Gloves       2.0      24.50   
2  Washington      Accessories  Tires and Tubes       3.0       3.67   
3  Washington      Accessories  Tires and Tubes       2.0      87.50   
4  Washington      Accessories  Tires and Tubes       3.0      35.00   

   Unit Price   Cost  Revenue  Column1  
0  109.000000   80.0    109.0      NaN  
1   28.500000   49.0     57.0      NaN  
2    5.000000   11.0     15.0      NaN  
3  116.500000  175.0    233.0      NaN  
4   41.666667  105.0    125.0      NaN

In [5]:
data = pd.read_csv('SalesForCourse_quizz_table.csv', index_col=0)

In [6]:
data.head()

Date    Year     Month  Customer Age Customer Gender  \
index                                                             
0      02/19/16  2016.0  February          29.0               F   
1      02/20/16  2016.0  February          29.0               F   
2      02/27/16  2016.0  February          29.0               F   
3      03/12/16  2016.0     March          29.0               F   
4      03/12/16  2016.0     March          29.0               F   

             Country       State Product Category     Sub Category  Quantity  \
index                                                                          
0      United States  Washington      Accessories  Tires and Tubes       1.0   
1      United States  Washington         Clothing           Gloves       2.0   
2      United States  Washington      Accessories  Tires and Tubes       3.0   
3      United States  Washington      Accessories  Tires and Tubes       2.0   
4      United States  Washington      Accessories  Tires and Tubes       3.0   

       Unit Cost  Unit Price   Cost  Revenue  Column1  
index                                                  
0          80.00  109.000000   80.0    109.0      NaN  
1          24.50   28.500000   49.0     57.0      NaN  
2           3.67    5.000000   11.0     15.0      NaN  
3          87.50  116.500000  175.0    233.0      NaN  
4          35.00   41.666667  105.0    125.0      NaN

In [7]:
data.Date.nunique()

576

In [8]:
data['Sub Category'].unique()

array(['Tires and Tubes', 'Gloves', 'Helmets', 'Bike Stands',
       'Mountain Bikes', 'Hydration Packs', 'Jerseys', 'Fenders',
       'Cleaners', 'Socks', 'Caps', 'Touring Bikes', 'Bottles and Cages',
       'Vests', 'Road Bikes', 'Bike Racks', 'Shorts', nan], dtype=object)

In [9]:
data['Product Category'].unique()

array(['Accessories', 'Clothing', 'Bikes', nan], dtype=object)

In [10]:
data[data['Sub Category'].isna() == True]

Date  Year Month  Customer Age Customer Gender Country State  \
index                                                                
34866  NaN   NaN   NaN           NaN             NaN     NaN   NaN   

      Product Category Sub Category  Quantity  Unit Cost  Unit Price  Cost  \
index                                                                        
34866              NaN          NaN       NaN        NaN         NaN   NaN   

          Revenue  Column1  
index                       
34866  641.532095      NaN

In [11]:
data['Column1'].unique()

array([        nan, 2370.      ,  398.      , ..., 1971.      ,
       1568.      ,  687.344828])

In [12]:
data['Customer Age'].unique()

array([29., 18., 19., 20., 22., 24., 40., 21., 23., 25., 30., 55., 53.,
       52., 51., 50., 49., 48., 47., 46., 45., 41., 42., 65., 64., 32.,
       33., 63., 34., 35., 43., 62., 37., 44., 60., 59., 58., 36., 61.,
       57., 54., 38., 39., 27., 28., 17., 26., 67., 66., 71., 31., 56.,
       87., 70., 69., 73., 68., 75., 86., 85., 77., 81., 84., 78., 72.,
       80., 74., 76., 79., 82., nan])

In [13]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [14]:
df.columns

Index(['date', 'year', 'month', 'customer_age', 'customer_gender', 'country',
       'state', 'product_category', 'sub_category', 'quantity', 'unit_cost',
       'unit_price', 'cost', 'revenue', 'column1'],
      dtype='object')

In [15]:
df = df.drop(columns='column1')

In [16]:
df.shape

(34867, 14)

In [17]:
df = df.dropna()

In [18]:
df.shape

(34866, 14)

In [19]:
df.dtypes

date                 object
year                float64
month                object
customer_age        float64
customer_gender      object
country              object
state                object
product_category     object
sub_category         object
quantity            float64
unit_cost           float64
unit_price          float64
cost                float64
revenue             float64
dtype: object

In [20]:
df.year.unique()

array([2016., 2015.])

In [21]:
df.year = df.year.astype(int)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34866 entries, 0 to 34865
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   date              34866 non-null  object 
 1   year              34866 non-null  int64  
 2   month             34866 non-null  object 
 3   customer_age      34866 non-null  float64
 4   customer_gender   34866 non-null  object 
 5   country           34866 non-null  object 
 6   state             34866 non-null  object 
 7   product_category  34866 non-null  object 
 8   sub_category      34866 non-null  object 
 9   quantity          34866 non-null  float64
 10  unit_cost         34866 non-null  float64
 11  unit_price        34866 non-null  float64
 12  cost              34866 non-null  float64
 13  revenue           34866 non-null  float64
dtypes: float64(6), int64(1), object(7)
memory usage: 4.0+ MB


In [23]:
df.customer_age.unique()

array([29., 18., 19., 20., 22., 24., 40., 21., 23., 25., 30., 55., 53.,
       52., 51., 50., 49., 48., 47., 46., 45., 41., 42., 65., 64., 32.,
       33., 63., 34., 35., 43., 62., 37., 44., 60., 59., 58., 36., 61.,
       57., 54., 38., 39., 27., 28., 17., 26., 67., 66., 71., 31., 56.,
       87., 70., 69., 73., 68., 75., 86., 85., 77., 81., 84., 78., 72.,
       80., 74., 76., 79., 82.])

In [24]:
df.customer_age = df.customer_age.astype(int)

In [25]:
df.quantity.unique()

array([1., 2., 3.])

In [26]:
df.quantity = df.quantity.astype(int)

In [27]:
df.unit_cost.unique()

array([8.0000e+01, 2.4500e+01, 3.6700e+00, 8.7500e+01, 3.5000e+01,
       6.6000e+01, 5.2000e+01, 6.0000e+01, 8.0000e+00, 2.5000e+00,
       1.7500e+01, 4.0000e+01, 4.6000e+01, 9.0000e+00, 1.5167e+02,
       7.0000e+01, 3.8500e+02, 7.2500e+01, 2.1000e+02, 6.4000e+01,
       3.2667e+02, 1.2500e+02, 2.1500e+02, 2.2000e+01, 7.5000e+02,
       1.4000e+02, 1.9250e+02, 3.8330e+01, 5.6000e+01, 1.0867e+02,
       1.4670e+01, 2.8000e+02, 2.9350e+02, 2.0000e+00, 4.2000e+02,
       2.7550e+02, 1.2000e+02, 6.3000e+02, 3.2500e+01, 3.3833e+02,
       1.0670e+01, 3.6670e+01, 2.4500e+02, 6.3600e+02, 1.5900e+02,
       7.6900e+02, 2.2950e+03, 1.1600e+03, 7.9750e+02, 1.8000e+02,
       2.3200e+03, 1.0000e+02, 1.3333e+02, 8.8000e+01, 3.0000e+02,
       5.9400e+02, 7.5000e+01, 9.9500e+01, 4.6670e+01, 1.7500e+02,
       5.2500e+01, 1.2250e+02, 4.5000e+01, 2.7000e+01, 2.1600e+02,
       5.3000e+02, 1.1130e+03, 2.4733e+02, 3.8450e+02, 4.7700e+02,
       1.6500e+02, 2.5667e+02, 7.1500e+02, 8.5000e+01, 1.0500e

In [28]:
df.unit_cost = round(df.unit_cost, 2)

In [29]:
df.unit_price = round(df.unit_price, 2)

In [30]:
df.cost = round(df.cost, 2)

In [31]:
df.revenue = round(df.revenue, 2)

In [32]:
df['total_price'] = df.quantity * df.unit_cost

In [33]:
df.head()

date  year     month  customer_age customer_gender        country  \
0  2016-02-19  2016  February            29               F  United States   
1  2016-02-20  2016  February            29               F  United States   
2  2016-02-27  2016  February            29               F  United States   
3  2016-03-12  2016     March            29               F  United States   
4  2016-03-12  2016     March            29               F  United States   

        state product_category     sub_category  quantity  unit_cost  \
0  Washington      Accessories  Tires and Tubes         1      80.00   
1  Washington         Clothing           Gloves         2      24.50   
2  Washington      Accessories  Tires and Tubes         3       3.67   
3  Washington      Accessories  Tires and Tubes         2      87.50   
4  Washington      Accessories  Tires and Tubes         3      35.00   

   unit_price   cost  revenue  total_price  
0      109.00   80.0    109.0        80.00  
1       28.50   49.0     57.0        49.00  
2        5.00   11.0     15.0        11.01  
3      116.50  175.0    233.0       175.00  
4       41.67  105.0    125.0       105.00

In [34]:
df.date = pd.to_datetime(df.date)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34866 entries, 0 to 34865
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   date              34866 non-null  datetime64[ns]
 1   year              34866 non-null  int64         
 2   month             34866 non-null  object        
 3   customer_age      34866 non-null  int64         
 4   customer_gender   34866 non-null  object        
 5   country           34866 non-null  object        
 6   state             34866 non-null  object        
 7   product_category  34866 non-null  object        
 8   sub_category      34866 non-null  object        
 9   quantity          34866 non-null  int64         
 10  unit_cost         34866 non-null  float64       
 11  unit_price        34866 non-null  float64       
 12  cost              34866 non-null  float64       
 13  revenue           34866 non-null  float64       
 14  total_price       3486

In [9]:
def get_cols(train):
    cat_cols, num_cols = [], []
    for col in train.columns:
        if train[col].dtype == 'O':
            cat_cols.append(col)
        elif train[col].dtype == 'datetime64[ns]':
            cat_cols.append(col)
        else:
            if train[col].nunique() < 10:
                cat_cols.append(col)
            else:
                num_cols.append(col)
    return cat_cols, num_cols

In [10]:
def encode_cat_variables(df, encode_cols):
    # encode categorical columns into numerical values that can be used in modeling
    # create encoder object
    le = LabelEncoder()
    for col in encode_cols:
        le.fit(df[col])
        # create a new column with the encoded values
        df[f'{col}_encoded'] = le.transform(df[col])
    return df

In [11]:
def one_hot_encode_columns(df, cols):
    # one-hot encode the outcome variable since that is our target
    df = pd.concat([df, 
                    pd.get_dummies(df[[cols]], 
                     dummy_na=False, 
                     drop_first=[True, True])], axis=1)
    return df

In [12]:
def prepare_data(df):
    '''
    this will clean the column names and change the data types to the proper dtypes.
    '''
    # change column names to lowercase and remove spaces
    df.columns = [col.lower().replace(' ', '_') for col in df.columns]
    
    # drop the column1 which has unknown data
    df = df.drop(columns='column1')
    # drop the 1 row containing null values in most of the row
    df = df.dropna()
    
    # change data types to int
    df.year = df.year.astype(int)
    df.customer_age = df.customer_age.astype(int)
    df.quantity = df.quantity.astype(int)
    
    # round dollar amounts to 2 digits
    df.unit_cost = round(df.unit_cost, 2)
    df.unit_price = round(df.unit_price, 2)
    df.cost = round(df.cost, 2)
    df.revenue = round(df.revenue, 2)
    
    # set date to datetime dtype
    df.date = pd.to_datetime(df.date)
    
    # create new column for total price of sale
    df['total_price'] = df.quantity * df.unit_price
    
    # one-hot encode 'sub-category' column
    df = one_hot_encode_columns(df, 'sub_category')
    # one-hot encode 'customer_gender' column
    df = one_hot_encode_columns(df, 'customer_gender')
    # one-hot encode 'country' column
    df = one_hot_encode_columns(df, 'country')
    
    #encode categorical varibles
    encode_cols = ['product_category']
    df = encode_cat_variables(df, encode_cols)
    
    # return the cleaned dataset
    return df

In [13]:
def split_data(df, random_seed=4233):
    '''
    split_data will take in a DataFrame and split it into train, validate and test sets
    random_seed is also asignable (default = 4233 for no reason).
    It will return the data split up for ML models. 
    The return values are: train, validate, test
    '''
    # split our df into train_val and test:
    train_val, test = train_test_split(df,
                                       train_size=0.8,
                                       random_state=random_seed)
    
    # split our train_val into train and validate:
    train, validate = train_test_split(train_val,
                                       train_size=0.7,
                                       random_state=random_seed)
    # return the split DataFrames
    return train, validate, test

In [14]:
def wrangle_data():
    '''
    This will perform the acquire, preparation and split functions with one command

    returns the clean df, train, validate and test
    '''
    # acquire and clean the data
    df = prepare_data(acquire_data())
    # split the data into train, validate and test
    train, validate, test = split_data(df)
    # return the clean df, train, validate and test
    return df, train, validate, test

In [25]:
def scale_data(train,
               validate,
               test,
               columns_to_scale=['customer_age'],
               scaler=StandardScaler(),
               return_scaler=False):
    '''
    Scales the 3 data splits. 
    Takes in train, validate, and test data splits and returns their scaled counterparts.
    If return_scalar is True, the scaler object will be returned as well
    '''
    # make copies of our original data so we dont gronk up anything
    train_scaled = train.copy()
    validate_scaled = validate.copy()
    test_scaled = test.copy()
    
    #     fit the thing
    scaler.fit(train[columns_to_scale])
    # applying the scaler:
    train_scaled[columns_to_scale] = pd.DataFrame(
        scaler.transform(train[columns_to_scale]),
        columns=train[columns_to_scale].columns.values, 
        index = train.index)
    # apply the scaller on the validation dataset                                    
    validate_scaled[columns_to_scale] = pd.DataFrame(
        scaler.transform(validate[columns_to_scale]),
        columns=validate[columns_to_scale].columns.values).set_index(
        [validate.index.values])
    # apply the scaler on the test dataset
    test_scaled[columns_to_scale] = pd.DataFrame(scaler.transform(
        test[columns_to_scale]), 
        columns=test[columns_to_scale].columns.values).set_index(
        [test.index.values])
    
    # if we requested the scaler returned in the function call,
    # then return the scaler object along with the scaled data
    if return_scaler:
        return scaler, train_scaled, validate_scaled, test_scaled
    # otherwise return the scaled data
    else:
        return train_scaled, validate_scaled, test_scaled

In [21]:
df, train, val, test = wrangle_data()

Opening data from local file.


In [18]:
df2.head()

date  year     month  customer_age customer_gender        country  \
0 2016-02-19  2016  February            29               F  United States   
1 2016-02-20  2016  February            29               F  United States   
2 2016-02-27  2016  February            29               F  United States   
3 2016-03-12  2016     March            29               F  United States   
4 2016-03-12  2016     March            29               F  United States   

        state product_category     sub_category  quantity  ...  \
0  Washington      Accessories  Tires and Tubes         1  ...   
1  Washington         Clothing           Gloves         2  ...   
2  Washington      Accessories  Tires and Tubes         3  ...   
3  Washington      Accessories  Tires and Tubes         2  ...   
4  Washington      Accessories  Tires and Tubes         3  ...   

   sub_category_Shorts  sub_category_Socks  sub_category_Tires and Tubes  \
0                    0                   0                             1   
1                    0                   0                             0   
2                    0                   0                             1   
3                    0                   0                             1   
4                    0                   0                             1   

   sub_category_Touring Bikes  sub_category_Vests  customer_gender_M  \
0                           0                   0                  0   
1                           0                   0                  0   
2                           0                   0                  0   
3                           0                   0                  0   
4                           0                   0                  0   

   country_Germany  country_United Kingdom  country_United States  \
0                0                       0                      1   
1                0                       0                      1   
2                0                       0                      1   
3                0                       0                      1   
4                0                       0                      1   

   product_category_encoded  
0                         0  
1                         2  
2                         0  
3                         0  
4                         0  

[5 rows x 36 columns]

In [27]:
train.head()

date  year      month  customer_age customer_gender  \
8366  2016-06-08  2016       June            30               M   
3413  2016-01-16  2016    January            25               F   
11230 2016-03-14  2016      March            26               F   
29743 2015-11-16  2015   November            79               M   
3176  2015-09-02  2015  September            46               F   

              country       state product_category       sub_category  \
8366   United Kingdom     England      Accessories    Tires and Tubes   
3413   United Kingdom     England      Accessories            Helmets   
11230   United States  California      Accessories  Bottles and Cages   
29743   United States  California         Clothing              Vests   
3176           France     Essonne            Bikes         Road Bikes   

       quantity  ...  sub_category_Helmets  sub_category_Hydration Packs  \
8366          2  ...                     0                             0   
3413          2  ...                     1                             0   
11230         2  ...                     0                             0   
29743         2  ...                     0                             0   
3176          1  ...                     0                             0   

       sub_category_Jerseys  sub_category_Mountain Bikes  \
8366                      0                            0   
3413                      0                            0   
11230                     0                            0   
29743                     0                            0   
3176                      0                            0   

       sub_category_Road Bikes  sub_category_Shorts  sub_category_Socks  \
8366                         0                    0                   0   
3413                         0                    0                   0   
11230                        0                    0                   0   
29743                        0                    0                   0   
3176                         1                    0                   0   

       sub_category_Tires and Tubes  sub_category_Touring Bikes  \
8366                              1                           0   
3413                              0                           0   
11230                             0                           0   
29743                             0                           0   
3176                              0                           0   

       sub_category_Vests  
8366                    0  
3413                    0  
11230                   0  
29743                   1  
3176                    0  

[5 rows x 31 columns]

In [85]:
train_scaled.loc[[8366]]

date  year month  customer_age customer_gender         country  \
8366 2016-06-08  2016  June     -0.572424               M  United Kingdom   

        state product_category     sub_category  quantity  ...  \
8366  England      Accessories  Tires and Tubes         2  ...   

      sub_category_Socks  sub_category_Tires and Tubes  \
8366                   0                             1   

      sub_category_Touring Bikes  sub_category_Vests  customer_gender_M  \
8366                           0                   0                  1   

      country_Germany  country_United Kingdom  country_United States  \
8366                0                       1                      0   

      product_category_encoded  cluster  
8366                         0        0  

[1 rows x 37 columns]

In [88]:
train_scaled, val_scaled, test_scaled = scale_data(train, val, test)

# Step 2: Customer Segmentation
from sklearn.cluster import AgglomerativeClustering

# Select relevant features for segmentation
features = ['customer_age', 'customer_gender_M', 'product_category_encoded']

# Apply Agglomerative Clustering to segment customers
clustering_model = AgglomerativeClustering(n_clusters=5)  # Choose the desired number of clusters
customer_labels = clustering_model.fit_predict(train_scaled[features])
train_scaled['cluster'] = customer_labels

# Step 3: Recommender System
def generate_recommendations(customer_id):
    target_customer = train_scaled.loc[[customer_id]]
#     print(target_customer)
    target_cluster = target_customer['cluster'].values[0]
#     print(target_cluster)
    cluster_customers = train_scaled.loc[df['cluster'] == target_cluster]
#     print(cluster_customers)
    popular_subcategories = cluster_customers['sub_category'].value_counts().index.tolist()
#     print(popular_subcategories)
    # Generate recommendations based on popular subcategories within the cluster
    recommendations = popular_subcategories[:5]  # Select the top 5 subcategories
    
    return recommendations

# Step 4: Testing and Evaluation
# Split the dataset into training and testing sets

In [89]:
# Apply the recommendation function to a test customer and evaluate the quality of recommendations
test_customer_id = 3176
recommendations = generate_recommendations(test_customer_id)
print(f"Recommendations for Customer {test_customer_id}: {recommendations}")

Recommendations for Customer 3176: ['Tires and Tubes', 'Bottles and Cages', 'Helmets', 'Road Bikes', 'Mountain Bikes']


In [90]:
# Apply the recommendation function to a test customer and evaluate the quality of recommendations
test_customer_id = 8366
recommendations = generate_recommendations(test_customer_id)
print(f"Recommendations for Customer {test_customer_id}: {recommendations}")

Recommendations for Customer 8366: ['Tires and Tubes', 'Bottles and Cages', 'Helmets', 'Mountain Bikes', 'Jerseys']


In [91]:
# Apply the recommendation function to a test customer and evaluate the quality of recommendations
test_customer_id = 11230
recommendations = generate_recommendations(test_customer_id)
print(f"Recommendations for Customer {test_customer_id}: {recommendations}")

Recommendations for Customer 11230: ['Tires and Tubes', 'Bottles and Cages', 'Helmets', 'Mountain Bikes', 'Jerseys']


In [92]:
# Apply the recommendation function to a test customer and evaluate the quality of recommendations
test_customer_id = 29743
recommendations = generate_recommendations(test_customer_id)
print(f"Recommendations for Customer {test_customer_id}: {recommendations}")

Recommendations for Customer 29743: ['Tires and Tubes', 'Bottles and Cages', 'Helmets', 'Road Bikes', 'Mountain Bikes']
