In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [55]:
def acquire_data():
    '''
    Acquire the sales dataset from local cached file or if local file
    does not exits, then download the data from data.world.
    '''
    # set the filename
    filename = 'sales.csv'
    if os.path.exists(filename):
        # if local file exists
        # display status message
        print('Opening data from local file.')
        # open the local data
        df = pd.read_csv(filename)
    else:
        # if the local file does not exist, download the data
        # display status message
        print('Local file not found')
        print('Downloading dataset')
        # download the data from data.world
        df = pd.read_excel('https://query.data.world/s/fhfoecpnngvcahqseb5ai6daubh4gk?dws=00000')
        # create a local cache of the data
        df.to_csv(filename, index=False)
        
    # return the acquired data
    return df

In [62]:
df = acquire_data()

Opening data from local file.


In [63]:
df.head()

Date    Year     Month  Customer Age Customer Gender        Country  \
0  2016-02-19  2016.0  February          29.0               F  United States   
1  2016-02-20  2016.0  February          29.0               F  United States   
2  2016-02-27  2016.0  February          29.0               F  United States   
3  2016-03-12  2016.0     March          29.0               F  United States   
4  2016-03-12  2016.0     March          29.0               F  United States   

        State Product Category     Sub Category  Quantity  Unit Cost  \
0  Washington      Accessories  Tires and Tubes       1.0      80.00   
1  Washington         Clothing           Gloves       2.0      24.50   
2  Washington      Accessories  Tires and Tubes       3.0       3.67   
3  Washington      Accessories  Tires and Tubes       2.0      87.50   
4  Washington      Accessories  Tires and Tubes       3.0      35.00   

   Unit Price   Cost  Revenue  Column1  
0  109.000000   80.0    109.0      NaN  
1   28.500000   49.0     57.0      NaN  
2    5.000000   11.0     15.0      NaN  
3  116.500000  175.0    233.0      NaN  
4   41.666667  105.0    125.0      NaN

In [4]:
data = pd.read_csv('SalesForCourse_quizz_table.csv', index_col=0)

In [5]:
data.head()

Date    Year     Month  Customer Age Customer Gender  \
index                                                             
0      02/19/16  2016.0  February          29.0               F   
1      02/20/16  2016.0  February          29.0               F   
2      02/27/16  2016.0  February          29.0               F   
3      03/12/16  2016.0     March          29.0               F   
4      03/12/16  2016.0     March          29.0               F   

             Country       State Product Category     Sub Category  Quantity  \
index                                                                          
0      United States  Washington      Accessories  Tires and Tubes       1.0   
1      United States  Washington         Clothing           Gloves       2.0   
2      United States  Washington      Accessories  Tires and Tubes       3.0   
3      United States  Washington      Accessories  Tires and Tubes       2.0   
4      United States  Washington      Accessories  Tires and Tubes       3.0   

       Unit Cost  Unit Price   Cost  Revenue  Column1  
index                                                  
0          80.00  109.000000   80.0    109.0      NaN  
1          24.50   28.500000   49.0     57.0      NaN  
2           3.67    5.000000   11.0     15.0      NaN  
3          87.50  116.500000  175.0    233.0      NaN  
4          35.00   41.666667  105.0    125.0      NaN

In [54]:
data.Date.nunique()

576

In [6]:
data['Sub Category'].unique()

array(['Tires and Tubes', 'Gloves', 'Helmets', 'Bike Stands',
       'Mountain Bikes', 'Hydration Packs', 'Jerseys', 'Fenders',
       'Cleaners', 'Socks', 'Caps', 'Touring Bikes', 'Bottles and Cages',
       'Vests', 'Road Bikes', 'Bike Racks', 'Shorts', nan], dtype=object)

In [7]:
data['Product Category'].unique()

array(['Accessories', 'Clothing', 'Bikes', nan], dtype=object)

In [8]:
data[data['Sub Category'].isna() == True]

Date  Year Month  Customer Age Customer Gender Country State  \
index                                                                
34866  NaN   NaN   NaN           NaN             NaN     NaN   NaN   

      Product Category Sub Category  Quantity  Unit Cost  Unit Price  Cost  \
index                                                                        
34866              NaN          NaN       NaN        NaN         NaN   NaN   

          Revenue  Column1  
index                       
34866  641.532095      NaN

In [9]:
data['Column1'].unique()

array([        nan, 2370.      ,  398.      , ..., 1971.      ,
       1568.      ,  687.344828])

In [10]:
data['Customer Age'].unique()

array([29., 18., 19., 20., 22., 24., 40., 21., 23., 25., 30., 55., 53.,
       52., 51., 50., 49., 48., 47., 46., 45., 41., 42., 65., 64., 32.,
       33., 63., 34., 35., 43., 62., 37., 44., 60., 59., 58., 36., 61.,
       57., 54., 38., 39., 27., 28., 17., 26., 67., 66., 71., 31., 56.,
       87., 70., 69., 73., 68., 75., 86., 85., 77., 81., 84., 78., 72.,
       80., 74., 76., 79., 82., nan])

In [11]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [12]:
df.columns

Index(['date', 'year', 'month', 'customer_age', 'customer_gender', 'country',
       'state', 'product_category', 'sub_category', 'quantity', 'unit_cost',
       'unit_price', 'cost', 'revenue', 'column1'],
      dtype='object')

In [13]:
df = df.drop(columns='column1')

In [14]:
df.shape

(34867, 14)

In [15]:
df = df.dropna()

In [16]:
df.shape

(34866, 14)

In [17]:
df.dtypes

date                datetime64[ns]
year                       float64
month                       object
customer_age               float64
customer_gender             object
country                     object
state                       object
product_category            object
sub_category                object
quantity                   float64
unit_cost                  float64
unit_price                 float64
cost                       float64
revenue                    float64
dtype: object

In [18]:
df.year.unique()

array([2016., 2015.])

In [19]:
df.year = df.year.astype(int)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34866 entries, 0 to 34865
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   date              34866 non-null  datetime64[ns]
 1   year              34866 non-null  int64         
 2   month             34866 non-null  object        
 3   customer_age      34866 non-null  float64       
 4   customer_gender   34866 non-null  object        
 5   country           34866 non-null  object        
 6   state             34866 non-null  object        
 7   product_category  34866 non-null  object        
 8   sub_category      34866 non-null  object        
 9   quantity          34866 non-null  float64       
 10  unit_cost         34866 non-null  float64       
 11  unit_price        34866 non-null  float64       
 12  cost              34866 non-null  float64       
 13  revenue           34866 non-null  float64       
dtypes: datetime64[ns](1), 

In [21]:
df.customer_age.unique()

array([29., 18., 19., 20., 22., 24., 40., 21., 23., 25., 30., 55., 53.,
       52., 51., 50., 49., 48., 47., 46., 45., 41., 42., 65., 64., 32.,
       33., 63., 34., 35., 43., 62., 37., 44., 60., 59., 58., 36., 61.,
       57., 54., 38., 39., 27., 28., 17., 26., 67., 66., 71., 31., 56.,
       87., 70., 69., 73., 68., 75., 86., 85., 77., 81., 84., 78., 72.,
       80., 74., 76., 79., 82.])

In [22]:
df.customer_age = df.customer_age.astype(int)

In [23]:
df.quantity.unique()

array([1., 2., 3.])

In [24]:
df.quantity = df.quantity.astype(int)

In [25]:
df.unit_cost.unique()

array([8.0000e+01, 2.4500e+01, 3.6700e+00, 8.7500e+01, 3.5000e+01,
       6.6000e+01, 5.2000e+01, 6.0000e+01, 8.0000e+00, 2.5000e+00,
       1.7500e+01, 4.0000e+01, 4.6000e+01, 9.0000e+00, 1.5167e+02,
       7.0000e+01, 3.8500e+02, 7.2500e+01, 2.1000e+02, 6.4000e+01,
       3.2667e+02, 1.2500e+02, 2.1500e+02, 2.2000e+01, 7.5000e+02,
       1.4000e+02, 1.9250e+02, 3.8330e+01, 5.6000e+01, 1.0867e+02,
       1.4670e+01, 2.8000e+02, 2.9350e+02, 2.0000e+00, 4.2000e+02,
       2.7550e+02, 1.2000e+02, 6.3000e+02, 3.2500e+01, 3.3833e+02,
       1.0670e+01, 3.6670e+01, 2.4500e+02, 6.3600e+02, 1.5900e+02,
       7.6900e+02, 2.2950e+03, 1.1600e+03, 7.9750e+02, 1.8000e+02,
       2.3200e+03, 1.0000e+02, 1.3333e+02, 8.8000e+01, 3.0000e+02,
       5.9400e+02, 7.5000e+01, 9.9500e+01, 4.6670e+01, 1.7500e+02,
       5.2500e+01, 1.2250e+02, 4.5000e+01, 2.7000e+01, 2.1600e+02,
       5.3000e+02, 1.1130e+03, 2.4733e+02, 3.8450e+02, 4.7700e+02,
       1.6500e+02, 2.5667e+02, 7.1500e+02, 8.5000e+01, 1.0500e

In [26]:
df.unit_cost = round(df.unit_cost, 2)

In [27]:
df.unit_price = round(df.unit_price, 2)

In [28]:
df.cost = round(df.cost, 2)

In [29]:
df.revenue = round(df.revenue, 2)

In [30]:
df['total_price'] = df.quantity * df.unit_cost

In [31]:
df.head()

date  year     month  customer_age customer_gender        country  \
0 2016-02-19  2016  February            29               F  United States   
1 2016-02-20  2016  February            29               F  United States   
2 2016-02-27  2016  February            29               F  United States   
3 2016-03-12  2016     March            29               F  United States   
4 2016-03-12  2016     March            29               F  United States   

        state product_category     sub_category  quantity  unit_cost  \
0  Washington      Accessories  Tires and Tubes         1      80.00   
1  Washington         Clothing           Gloves         2      24.50   
2  Washington      Accessories  Tires and Tubes         3       3.67   
3  Washington      Accessories  Tires and Tubes         2      87.50   
4  Washington      Accessories  Tires and Tubes         3      35.00   

   unit_price   cost  revenue  total_price  
0      109.00   80.0    109.0        80.00  
1       28.50   49.0     57.0        49.00  
2        5.00   11.0     15.0        11.01  
3      116.50  175.0    233.0       175.00  
4       41.67  105.0    125.0       105.00

In [32]:
def prepare_data(df):
    '''
    this will clean the column names and change the data types to the proper dtypes.
    '''
    # change column names to lowercase and remove spaces
    df.columns = [col.lower().replace(' ', '_') for col in df.columns]
    # drop the column1 which has unknown data
    df = df.drop(columns='column1')
    # drop the 1 row containing null values in most of the row
    df = df.dropna()
    # change data types to int
    df.year = df.year.astype(int)
    df.customer_age = df.customer_age.astype(int)
    df.quantity = df.quantity.astype(int)
    # round dollar amounts to 2 digits
    df.unit_cost = round(df.unit_cost, 2)
    df.unit_price = round(df.unit_price, 2)
    df.cost = round(df.cost, 2)
    df.revenue = round(df.revenue, 2)
    # create new column for total price of sale
    df['total_price'] = df.quantity * df.unit_cost
    # return the cleaned dataset
    return df

In [33]:
def split_data(df, random_seed=4233):
    '''
    split_data will take in a DataFrame and split it into train, validate and test sets
    random_seed is also asignable (default = 4233 for no reason).
    It will return the data split up for ML models. 
    The return values are: train, validate, test
    '''
    # split our df into train_val and test:
    train_val, test = train_test_split(df,
                                       train_size=0.8,
                                       random_state=random_seed)
    
    # split our train_val into train and validate:
    train, validate = train_test_split(train_val,
                                       train_size=0.7,
                                       random_state=random_seed)
    # return the split DataFrames
    return train, validate, test

In [34]:
def wrangle_data():
    '''
    This will perform the acquire, preparation and split functions with one command

    returns the clean df, train, validate and test
    '''
    # acquire and clean the data
    df = prepare_data(acquire_data())
    # split the data into train, validate and test
    train, validate, test = split_data(df)
    # return the clean df, train, validate and test
    return df, train, validate, test

In [35]:
df2, train, val, test = wrangle_data()

Local file not found


In [36]:
df2

date  year     month  customer_age customer_gender        country  \
0     2016-02-19  2016  February            29               F  United States   
1     2016-02-20  2016  February            29               F  United States   
2     2016-02-27  2016  February            29               F  United States   
3     2016-03-12  2016     March            29               F  United States   
4     2016-03-12  2016     March            29               F  United States   
...          ...   ...       ...           ...             ...            ...   
34861 2015-03-22  2015     March            38               M         France   
34862 2016-02-07  2016  February            38               M         France   
34863 2015-03-13  2015     March            38               M         France   
34864 2015-04-05  2015     April            38               M         France   
34865 2015-08-30  2015    August            38               M         France   

                   state product_category     sub_category  quantity  \
0             Washington      Accessories  Tires and Tubes         1   
1             Washington         Clothing           Gloves         2   
2             Washington      Accessories  Tires and Tubes         3   
3             Washington      Accessories  Tires and Tubes         2   
4             Washington      Accessories  Tires and Tubes         3   
...                  ...              ...              ...       ...   
34861  Charente-Maritime            Bikes   Mountain Bikes         1   
34862     Hauts de Seine            Bikes   Mountain Bikes         2   
34863     Hauts de Seine            Bikes   Mountain Bikes         1   
34864     Hauts de Seine            Bikes   Mountain Bikes         3   
34865     Hauts de Seine            Bikes   Mountain Bikes         1   

       unit_cost  unit_price    cost  revenue  total_price  
0          80.00      109.00    80.0    109.0        80.00  
1          24.50       28.50    49.0     57.0        49.00  
2           3.67        5.00    11.0     15.0        11.01  
3          87.50      116.50   175.0    233.0       175.00  
4          35.00       41.67   105.0    125.0       105.00  
...          ...         ...     ...      ...          ...  
34861    2049.00     1487.00  2049.0   1487.0      2049.00  
34862    1160.00      985.50  2320.0   1971.0      2320.00  
34863    2049.00     1583.00  2049.0   1583.0      2049.00  
34864     683.00      560.67  2049.0   1682.0      2049.00  
34865    2320.00     1568.00  2320.0   1568.0      2320.00  

[34866 rows x 15 columns]